# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project
name: aws-hello-world-ubuntu

# label should be a human readable label that conveys what this skillet will do
label: AWS Single Ubuntu Instance

# description is a longer more informative version of a label
description: Uses Terraform to launch a single Ubuntu Compute instance in AWS

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, labels can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: aws
  collection:
    - Public Cloud
    - Deploy

# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: access_key
    description: AWS Access Key
    default: Place your Access Key
    type_hint: text
  - name: secret_key
    description: AWS Secret Key
    default:
    type_hint: password
  - name: region
    description: AWS Region
    default: us-east-2
    type_hint: text
